import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="min-h-dvh bg-background px-4 py-10 text-foreground">
      <div className="mx-auto grid max-w-3xl gap-8">
        <div className="space-y-3">
          <Link href="/login" className="text-sm text-muted-foreground hover:text-foreground">
            Back to sign in
          </Link>
          <h1 className="text-3xl font-semibold tracking-tight">Terms of Service</h1>
          <p className="text-sm text-muted-foreground">Last updated June 21, 2026</p>
        </div>

        <section className="grid gap-3">
          <h2 className="text-lg font-semibold">Use of MakerMetrics</h2>
          <p className="text-sm leading-6 text-muted-foreground">
            MakerMetrics helps Etsy sellers analyze CSV exports from their own shops. You are
            responsible for the data you upload and for using the dashboard in a lawful,
            appropriate way.
          </p>
        </section>

        <section className="grid gap-3">
          <h2 className="text-lg font-semibold">Your Data</h2>
          <p className="text-sm leading-6 text-muted-foreground">
            Imported Etsy CSV data is used to show analytics inside your account. MakerMetrics
            does not need Etsy API access and deliberately avoids storing street addresses for
            analytics.
          </p>
        </section>

        <section className="grid gap-3">
          <h2 className="text-lg font-semibold">AI Features</h2>
          <p className="text-sm leading-6 text-muted-foreground">
            If you connect your own AI provider API key, responses are generated by that
            provider using the analytics context needed to answer your question. Review your
            provider&apos;s terms and billing before using AI features.
          </p>
        </section>

        <section className="grid gap-3">
          <h2 className="text-lg font-semibold">No Guarantees</h2>
          <p className="text-sm leading-6 text-muted-foreground">
            Forecasts, insights, and AI responses are informational and may be wrong,
            incomplete, or unsuitable for a specific business decision. Use your own judgment
            before acting on them.
          </p>
        </section>

        <section className="grid gap-3">
          <h2 className="text-lg font-semibold">Open Source License</h2>
          <p className="text-sm leading-6 text-muted-foreground">
            The MakerMetrics source code is provided under the MIT License. These service
            terms do not replace the repository license for the open source code.
          </p>
        </section>
      </div>
    </main>
  );
}
